### ISSUE TITLE
Reach out e-mail 'AnonymousUser' needs permission

### ISSUE THREAD

**Issue by SimonBartonPSU** [Capstone-SS-2020-PDX/Covid-19-MutualAid#249]
**Describe the bug**
If you try to use Reach Out feature, Django returns a 550 'Unauthenticated senders not allowed'. We need to allow commongoodsmail@gmail.com permission to do it's thang after tightening perms. Currently sender is 'AnonymousUser'.

Issue affects both iOS and Android. Most perniciously, the front end modal still reports 'Success'.

Associated relevant bits of stack trace:

(550, b'Unauthenticated senders not allowed', 'commongoodsmail@gmail.com')
Request Method: POST
Request URL: http://ace-mote-270703.wl.r.appspot.com/postings/contact/
Django Version: 3.0.8
Python Executable: /usr/local/bin/python3
Python Version: 3.8.5
Python Path: ['/code', '/usr/local/lib/python38.zip', '/usr/local/lib/python3.8', '/usr/local/lib/python3.8/lib-dynload', '/usr/local/lib/python3.8/site-packages']
Server time: Thu, 30 Jul 2020 03:56:32 +0000
...
Traceback (most recent call last):  

  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/code/cgapi/views.py", line 57, in contact
    email.send()
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "/usr/local/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/local/lib/python3.8/smtplib.py", line 871, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
`Exception Type: SMTPSenderRefused at /postings/contact/
Exception Value: (550, b'Unauthenticated senders not allowed', 'commongoodsmail@gmail.com')
Request information:
USER: AnonymousUser`
GET: No GET data
POST: No POST data
FILES: No FILES data
COOKIES: No cookie data
META:
CONTENT_LENGTH = '43'
CONTENT_TYPE = 'application/json'

No more needed, I don't think.

**Expected behavior**
Request e-mail is sent to appropriate user.

**Comment by EHaake** [comment]
Nice catch. We'll hopefully get it fixed soon
