### ISSUE TITLE
Map crashes on iOS

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#266]
## Issue Description
The `react-native-maps` crashes on iOS. There is no error message, Expo just crashes.

**To Reproduce**
1. Login
2. Go to Feed Screen
3. Tap on Posting Item with Maps enabled
4. Watch as Expo Crashes and you don't get an error message.

**Expected behavior**
Expo just crashes.

**iOS, Android, both?**
just iOS

**Devices tested:**
 - Device: [e.g. iPhone6s +]

**Additional context**
Maps are conditionally rendered so to reproduce, you'll need to go to the PostingDetailScreen.js file and remove the conditional rendering to render the map view on the detail screen unconditionally.

**Comment by EHaake** [comment]
Once, I got this message in the console after it crashed on iOS:

> BadRequestError: request aborted
>     at IncomingMessage.onAborted (/home/erik/.npm-global/lib/node_modules/expo-cli/node_modules/raw-body/index.js:231:10)
>     at IncomingMessage.emit (events.js:198:13)
>     at abortIncoming (_http_server.js:462:9)
>     at socketOnClose (_http_server.js:455:3)
>     at Socket.emit (events.js:203:15)
>     at TCP._handle.close (net.js:607:12)
>

**Comment by EHaake** [comment]
Ok weird. After reviewing allie's front-end-elements branch, Expo would sometimes crash when navigating to a detail screen with a map on iOS and sometimes not. It seemed initially to only crash on postings that have valid locations (not reversed long/lat) but it worked with some of those as well. I have no idea why it sometimes crashes and sometimes doesn't.  Will keep updating here if I figure out more.

**Comment by EHaake** [comment]
Closing since it appears, it only crashes on iOS if the lat and long values are reversed and invalid. Since that won't be the case going forward, closing this issue.
